import type { Movie } from '@/types';

export const allMovies: Movie[] = [
  {
    id: 'cosmic-odyssey',
    title: 'Cosmic Odyssey',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Cosmic\\nOdyssey',
    posterAiHint: 'space galaxy',
    rating: 4.8,
    genres: ['Sci-Fi', 'Adventure'],
    duration: 169,
    releaseYear: 2023,
    reviews: [
      { id: 1, author: 'Alex Drake', avatarUrl: 'https://i.pravatar.cc/150?u=alex', rating: 5, comment: 'A mind-bending masterpiece! The visuals were stunning.' },
      { id: 2, author: 'Mia Wong', avatarUrl: 'https://i.pravatar.cc/150?u=mia', rating: 4, comment: 'Great story, but a bit slow in the middle.' },
    ],
  },
  {
    id: 'echoes-of-the-past',
    title: 'Echoes of the Past',
    description: 'A historian discovers a secret that changes her understanding of the past, putting her life in danger.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Echoes+of\\nthe+Past',
    posterAiHint: 'ancient ruins',
    rating: 4.5,
    genres: ['Thriller', 'Mystery'],
    duration: 124,
    releaseYear: 2022,
    reviews: [
      { id: 1, author: 'John Smith', avatarUrl: 'https://i.pravatar.cc/150?u=john', rating: 5, comment: 'Kept me on the edge of my seat!' },
    ],
  },
  {
    id: 'neon-city-ronin',
    title: 'Neon City Ronin',
    description: 'In a futuristic cyberpunk city, a lone warrior seeks revenge against the corporation that wronged him.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Neon+City\\nRonin',
    posterAiHint: 'neon city',
    rating: 4.2,
    genres: ['Action', 'Sci-Fi'],
    duration: 135,
    releaseYear: 2024,
    reviews: [],
  },
  {
    id: 'the-last-laugh',
    title: 'The Last Laugh',
    description: 'A group of comedians plan a heist during their final show together. What could possibly go wrong?',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=The+Last\\nLaugh',
    posterAiHint: 'stage lights',
    rating: 3.9,
    genres: ['Comedy', 'Crime'],
    duration: 108,
    releaseYear: 2023,
    reviews: [
      { id: 1, author: 'Jane Doe', avatarUrl: 'https://i.pravatar.cc/150?u=jane', rating: 4, comment: 'Hilarious and clever. A must-watch!' },
    ],
  },
  {
    id: 'beneath-the-surface',
    title: 'Beneath the Surface',
    description: 'A documentary exploring the hidden world of deep-sea creatures and the impact of climate change.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Beneath+the\\nSurface',
    posterAiHint: 'deep ocean',
    rating: 4.9,
    genres: ['Documentary'],
    duration: 92,
    releaseYear: 2024,
    reviews: [],
  },
  {
    id: 'whispering-woods',
    title: 'Whispering Woods',
    description: 'A family on a camping trip gets lost in a forest inhabited by a mysterious entity.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Whispering\\nWoods',
    posterAiHint: 'dark forest',
    rating: 4.0,
    genres: ['Horror', 'Supernatural'],
    duration: 99,
    releaseYear: 2022,
    reviews: [],
  },
    {
    id: 'galaxy-racers',
    title: 'Galaxy Racers',
    description: 'In a distant galaxy, a young pilot joins an intergalactic racing tournament to save her home planet.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Galaxy\\nRacers',
    posterAiHint: 'space race',
    rating: 4.3,
    genres: ['Animation', 'Sci-Fi', 'Family'],
    duration: 110,
    releaseYear: 2023,
    reviews: [
      { id: 1, author: 'KidCritic', avatarUrl: 'https://i.pravatar.cc/150?u=kid', rating: 5, comment: 'Super fast and fun! The aliens are cool.' },
    ],
  },
  {
    id: 'the-chefs-table',
    title: 'The Chef\'s Table',
    description: 'An aspiring chef gets a chance to work at a world-renowned restaurant, only to find the head chef is her biggest rival.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=The+Chef\'s\\nTable',
    posterAiHint: 'gourmet food',
    rating: 4.1,
    genres: ['Drama', 'Romance'],
    duration: 118,
    releaseYear: 2024,
    reviews: [],
  },
];

export const allGenres = [...new Set(allMovies.flatMap(movie => movie.genres))].sort();
