import type { Movie } from '@/types';

export const allMovies: Movie[] = [
  {
    id: 'vikram',
    title: 'Vikram',
    description: 'A black-ops squad commander goes after a mysterious group of masked men who have declared war on the system.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Vikram',
    posterAiHint: 'action thriller',
    rating: 4.7,
    genres: ['Action', 'Thriller'],
    duration: 175,
    releaseYear: 2022,
    reviews: [
      { id: 1, author: 'Anbu', avatarUrl: 'https://i.pravatar.cc/150?u=anbu', rating: 5, comment: 'An absolute blast from start to finish. A true comeback!' },
      { id: 2, author: 'Priya', avatarUrl: 'https://i.pravatar.cc/150?u=priya', rating: 4, comment: 'Great action sequences, but the plot can be a bit confusing.' },
    ],
    showtimes: [
      { screen: 1, time: '4:30 PM' },
      { screen: 1, time: '8:00 PM' },
      { screen: 7, time: '5:00 PM' },
      { screen: 7, time: '9:30 PM' },
    ],
  },
  {
    id: 'leo',
    title: 'Leo',
    description: 'A mild-mannered café owner becomes a local hero through an act of violence, which sets off repercussions with a drug cartel that believes he was once a part of them.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Leo',
    posterAiHint: 'action crime',
    rating: 4.5,
    genres: ['Action', 'Thriller', 'Crime'],
    duration: 164,
    releaseYear: 2023,
    reviews: [
      { id: 1, author: 'Karthik', avatarUrl: 'https://i.pravatar.cc/150?u=karthik', rating: 5, comment: 'Thalapathy Vijay at his absolute best. The hyena fight was insane!' },
    ],
    showtimes: [
      { screen: 2, time: '6:00 PM' },
      { screen: 2, time: '8:45 PM' },
      { screen: 8, time: '10:00 PM' },
    ],
  },
  {
    id: 'jailer',
    title: 'Jailer',
    description: 'A retired jailer goes on a manhunt to find his son\'s killers. But the road leads him to a familiar, albeit a bit darker place.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Jailer',
    posterAiHint: 'action comedy',
    rating: 4.2,
    genres: ['Action', 'Comedy', 'Crime'],
    duration: 168,
    releaseYear: 2023,
    reviews: [],
    showtimes: [
      { screen: 3, time: '5:30 PM' },
      { screen: 3, time: '9:00 PM' },
    ],
  },
  {
    id: 'ponniyin-selvan-1',
    title: 'Ponniyin Selvan: I',
    description: 'Vandiyathevan, a brave and adventurous warrior, sets out to cross the Chola land to deliver a message from the crown prince Aditha Karikalan.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Ponniyin%5CnSelvan+I',
    posterAiHint: 'historical drama',
    rating: 4.6,
    genres: ['Action', 'Drama', 'History'],
    duration: 167,
    releaseYear: 2022,
    reviews: [
      { id: 1, author: 'Meena', avatarUrl: 'https://i.pravatar.cc/150?u=meena', rating: 5, comment: 'A visual spectacle! Mani Ratnam is a genius.' },
    ],
    showtimes: [
      { screen: 4, time: '7:00 PM' },
      { screen: 4, time: '9:15 PM' },
    ],
  },
  {
    id: 'kaithi',
    title: 'Kaithi',
    description: 'An ex-convict tries to meet his daughter for the first time after leaving prison but his attempts are interrupted by a drug raid.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Kaithi',
    posterAiHint: 'intense thriller',
    rating: 4.8,
    genres: ['Action', 'Thriller'],
    duration: 145,
    releaseYear: 2019,
    reviews: [],
    showtimes: [
      { screen: 5, time: '4:00 PM' },
      { screen: 5, time: '6:15 PM' },
    ],
  },
  {
    id: 'soorarai-pottru',
    title: 'Soorarai Pottru',
    description: 'A young man from a remote village dreams of launching his own airline service. However, he must overcome several obstacles to achieve his goal.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Soorarai%5CnPottru',
    posterAiHint: 'inspirational drama',
    rating: 4.9,
    genres: ['Drama'],
    duration: 153,
    releaseYear: 2020,
    reviews: [
       { id: 1, author: 'Ravi', avatarUrl: 'https://i.pravatar.cc/150?u=ravi', rating: 5, comment: 'Incredibly inspiring and well-acted. Suriya was fantastic.' },
    ],
    showtimes: [
      { screen: 6, time: '8:30 PM' },
      { screen: 6, time: '10:30 PM' },
    ],
  },
    {
    id: '96',
    title: '96',
    description: 'Two high school sweethearts from the batch of 1996 meet at a reunion and reminisce about their past.',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=96',
    posterAiHint: 'romantic nostalgia',
    rating: 4.8,
    genres: ['Romance', 'Drama'],
    duration: 158,
    releaseYear: 2018,
    reviews: [
      { id: 1, author: 'Janani', avatarUrl: 'https://i.pravatar.cc/150?u=janani', rating: 5, comment: 'A beautiful and heart-touching love story.' },
    ],
    showtimes: [
      { screen: 1, time: '11:00 AM' },
      { screen: 1, time: '1:30 PM' },
    ],
  },
  {
    id: 'asuran',
    title: 'Asuran',
    description: 'The teenage son of a farmer from an underprivileged community kills a rich, upper-class landlord. Will the farmer, a loving father and a pacifist by nature, be able to save his hot-headed son?',
    posterUrl: 'https://placehold.co/400x600/000/FFF?text=Asuran',
    posterAiHint: 'village action',
    rating: 4.7,
    genres: ['Action', 'Drama'],
    duration: 141,
    releaseYear: 2019,
    reviews: [],
    showtimes: [
      { screen: 2, time: '5:45 PM' },
    ],
  },
];

export const allGenres = [...new Set(allMovies.flatMap(movie => movie.genres))].sort();
